Feature/import assets
Manuel-Nunes/GameJam2023 pull request #3
Opened 2023-08-28 18:14 UTC by Manuel-Nunes

2023-08-28 18:16 UTC, Palesa-Mpe approved these changes

2023-08-28 18:51 UTC, raagakrishna requested changes

2023-08-28 18:51 UTC, raagakrishna commented on Assets/Scripts/PlayerTPLocationDefinition.cs
> +public class PlayerTPLocationDefinition : MonoBehaviour
Can you use the full word Teleport here? 
So `PlayerTeleportLocationDefinition`?

2023-08-28 18:53 UTC, raagakrishna requested changes

2023-08-28 18:53 UTC, raagakrishna commented on Assets/Scripts/PlayerMovement.cs
> +    private static Vector3 getTPLocation( GameObject player, bool isInPast){
Can we rename the function to `GetTeleportLocation`?

2023-08-28 18:53 UTC, raagakrishna commented on Assets/Scripts/PlayerMovement.cs
> +    public PlayerTPLocationDefinition PlayerTP;
Can we make the variable name here to `PlayerTeleport`?

2023-08-28 18:53 UTC, raagakrishna commented on Assets/Scripts/PlayerMovement.cs
> +    public bool isInPast = true;
It looks like you are using CamelCase for public variables, then can we make this `IsInPast`?

2023-08-29 05:58 UTC, raagakrishna requested changes

2023-08-29 05:58 UTC, raagakrishna commented on Assets/Scripts/PlayerMovement.cs
> +    private static Vector3 getTPLocation( GameObject player, bool isInPast){
Any feedback on this comment?

2023-08-29 05:58 UTC, raagakrishna commented on Assets/Scripts/PlayerMovement.cs
> +    public bool isInPast = true;
Any feedback on this comment?

2023-08-29 19:17 UTC, raagakrishna approved these changes

2023-08-29 19:27 UTC, merged